### ISSUE TITLE
Context browser doesnt always open to the right view

### ISSUE THREAD

**Issue by talimarcus** [predixdesignsystem/px-context-browser#78]
Related to the bug fixed in #77: https://github.com/PredixDev/px-context-browser/pull/77/commits/0a3f2a8c715e5533cf91ee749013b3520c629005 

1. When I go to the Demo page and refresh
2. Open the Context Browser in the "Basic" tab
3. Then go to the "Advanced" tab
4. Open the Context Browser in there
5. It opens to the previously selected state (from the "Basic" tab), rather than the currently selectedRoute. It does SELECT the right thing, and when I navigate to that level I can see that the correct item is selected, but it does not open to the correct level.

Same thing happens if I start by opening the CB in the "Advanced" tab then in "Basic."

**Comment by lmesta** [comment]
It also happens to me
View not display the correct px-context-browser
and i don't see a method to render again
