### ISSUE TITLE
Floating context browser on scroll.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-context-browser#82]
Noticed this while reviewing the demo site.

If you open the context browser and leave it open while scrolling up/down using the browser scroll bar, the open panel is locked in the original location and floats on top of the page as you scroll. 

![screen shot 2017-08-29 at 10 45 14 am](https://user-images.githubusercontent.com/10835611/29835557-3e14098c-8ca7-11e7-8140-2ccbcbe572f0.png)

**Comment by davidrleonard** [comment]
This is related to https://github.com/PolymerElements/iron-overlay-behavior/issues/140. We use iron-overlay-behavior (through iron-dropdown) to manage the context browser's state inside a scrollable region.
