### ISSUE TITLE
Items array not updated when children are added dynamically

### ISSUE THREAD

**Issue by akshayeshenoi** [predixdesignsystem/px-context-browser#87]
If I use the `addChildren()` function to add children to an item, the `items` array is not updated accordingly. This causes problem in item selection and updating the route for other elements like `px-breadcrumbs`. 
Even the `children` array for the `active` object seems to be always empty.

**Comment by akshayeshenoi** [comment]
Any update on this? 
The only way I've gotten around this is by updating the `items` array which forces the context browser to reset to the root level. It's an unpleasant experience to an otherwise excellent element, and we need to ship our product soon. 

Thanks!

**Comment by davidrleonard** [comment]
Let me dig into this a bit more and think about the best approach to solving it. 

The previous context browser did a lot of mutations to the underlying items passed in and caused headaches for maintaining the state of the items object over time as users interacted with an app. The new implementation was designed to allow the app to own the items object and avoid mutating it, especially so it could be shared across px components. But I see how addChildren not being picked up by a px-breadcrumbs component sharing the items object causes headaches. 

Any thoughts on how you imagine this working without causing confusion about where changes to the items object happen are welcome.

**Comment by Shibham** [comment]
I am facing the same issue. Any update on this ?

**Comment by Shibham** [comment]
For me there were duplicate children added to a node as node was not getting updated when we called addChildren on it.

I have found a workaround by maintaining a map of node values and whether children are added for them or not. So now addChildren will only be called on a node when it has not been called before. If called once, it will not be called for that node.

Thanks,
Shibha

**Comment by davidrleonard** [comment]
Thanks for adding additional info to help us fix this, @Shibham. I know it's an issue that needs to be resolved soon. We're looking for a fix that will allow for a good developer experience of adding children throughout the lifecycle of an app and keeping those changes in sync with a shared data model representing all the items.

While we work on that fix, you could solve temporarily your issue of knowing if a node is already added to the graph using a private API. This API isn't explicitly available right now and might change, but it can help you bridge the gap as we solve the issue long-term.

Before adding children, you can call the `_assetGraph.hasNode()` method with a reference to the item you'd like to add to see if it is already in the graph. Note that this will only work if you're using references, not if you'd using different objects that share the same data. 

Here's the docs for that method:

```
    /**
     * Checks if the node is in the graph.
     *
     * @param  {Object} node
     * @return {boolean}
     */
hasNode(node: Object): bool
```

You could call it like this:

```
// Get a reference to the browser HTMLElement in the DOM
var contextBrowser = document.querySelector('px-context-browser');
// newItem is a new child that may have been added already
var alreadyAdded = contextBrowser._assetGraph.hasNode(newItem);
```

**Comment by akshayeshenoi** [comment]
You can also use the `activeMeta` property's `children` array to find out if you need to add children. However this would be advisable only if you add all children at once (by making use of `activeMeta.children.length > 0 ? ` condition). Adding children separately would mean looping through the array and matching key values.

**Comment by akshayeshenoi** [comment]
Is there anyway I can add children to a node using its route?
`addChildren()` requires a direct reference of the node.

**Comment by davidrleonard** [comment]
We're still resolving some of these APIs. There's a private API that you can use to find a node by route. It'll return a reference to the node that you can use to call `addChildren`. It's at `_assetGraph.getNodeAtRoute(Array<id>, idKey)`. 

If you didn't change the default id key for items, you don't have to pass `idKey`.
