### ISSUE TITLE
Multi-select support in px-context-browser

### ISSUE THREAD

**Issue by shrau94** [predixdesignsystem/px-context-browser#94]
Hi,

I was trying to explore PX context browser for one of our use case. It supports most of our requirements except for selecting multiple nodes. I believe there is support for multi select in current version of context browser. 
Since demo page does not have this functionality enabled by default, can you please help us enable this? 

## Expected behavior:
https://github.com/PredixDev/px-context-browser/pull/44/files/2ddd39ba742fdc1606fafc4121740ebc6fc39475
I believe support was added after this pull request. It also provides checkboxes for each node which is kind of our requirement.
![image](https://user-images.githubusercontent.com/10210384/34289542-0b60ed94-e719-11e7-9831-216aca12d7d9.png)

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
component version no: 2.0.14

**Comment by randyaskin** [comment]
As stated on the discussion page of that PR, the code was **not** merged into the px-context-browser, as it is based on an older implementation. Context browser enhancements are currently in our roadmap for Q1 2018, although I do not know if multi-select is included in that list.

**Comment by shrau94** [comment]
When can we expect this enhancement to be taken up?
