### ISSUE TITLE
First context browser column doesn't render in Polymer 2.x

### ISSUE THREAD

**Issue by davidrleonard** [predixdesignsystem/px-context-browser#97]
In Polymer 2.x, when the context browser is first opened if no item is initially selected the first column doesn't render.

px-context-browser version: 2.1.1 (broken in any 2.1.0+ release)
Polymer version: 2.4.0 (broken in any 2.x release)
browser: Chrome 64 (OSX)

### Steps to reproduce

1. Create a px-context-browser instance on the page
2. Provide some valid `items`
3. Bind a trigger
4. Open the context browser

Expected outcome: The root items will be visible
Actual outcome: The context browser has the correct height but no visible items

### Cause

Seems to be a timing problem. The issue is here, though it may be present in more places as well:

https://github.com/PredixDev/px-context-browser/blob/1f81e30ddf39e36394e5aa2c373980695eefd9e2/px-context-browser-columns.html#L61-L68

In Polymer 1.x, it seems like the observer for `active` changing wouldn't run until the template was first stamped. Now, it runs before the template is stamped, so the DOM query for the next column comes back `null`. We'll need to do something to make sure we don't try this the first time until after we render, perhaps by adding an `_isReady` property we flip to true in a Polymer.RenderStatus.afterNextRender() callback invoked in attached.

We likely didn't catch this in the demo/elsewhere because we often set the selected item with data binding in our demos instead of showing the user the root items and letting them select something the first time.

![image](https://user-images.githubusercontent.com/6456757/35655628-a030e660-06a7-11e8-94e6-7458b6dbfe29.png)

**Comment by patrick-bergeron** [comment]
Hi David, thanks for catching this. Thought I was going a bit crazy there for a second trying various work-arounds. Any idea on when a fix will be available?

**Comment by mtbradle-ge** [comment]
Subscribing. Our team is starting a new app on Polymer 2 and also discovered this issue. Current workaround is to provide a static default item with no label, so it is invisible to the user. When data gets loaded it is replaced with the actual items and the first column becomes visible:

`
contextBrowserItems: {
type: Array,
  value: [{
    id: 'fake-item',
    label: ''
  }],
}
`

Messy. Would also like to know if there is any update on when a fix will be available.

Thanks.
